services:
  - type: web
    name: arpochat
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: HF_TOKEN
        sync: false
      - key: HF_HOME
        value: /tmp/.cache/huggingface
      - key: HF_HUB_CACHE
        value: /tmp/.cache/huggingface/hub
      - key: TORCH_HOME
        value: /tmp/.cache/torch
      - key: LOG_LEVEL
        value: info
    plan: free
    disk:
      name: cache
      mountPath: /tmp/.cache
      sizeGB: 10
    healthCheckPath: /health
    autoDeploy: true
    numInstances: 1 