services:
  - type: web
    name: arpochat
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT --workers 1 --log-level info
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: TRANSFORMERS_CACHE
        value: /tmp/.cache/huggingface
      - key: TORCH_HOME
        value: /tmp/.cache/torch
      - key: LOG_LEVEL
        value: info
    healthCheckPath: /health
    autoDeploy: true
    numInstances: 1
    plan: free